### ISSUE TITLE
フォローを連続 or 別タブで同時にした場合

### ISSUE THREAD

**Issue by hosaka555** [takayama-kento/twitter_clone#4]
フォロー連続 or 別タブで同時にした場合

**Comment by takayama-kento** [comment]
確認するために以下のテストを加えたところ，しっかり通りました．

https://github.com/takayama-kento/twitter_clone/blob/f7f63b1a14d85357250c645b0dc201ffba4eadaf/Laravel/tests/Feature/FollowApiTest.php#L42-L49
